apiVersion: apps/v1
kind: Deployment
metadata:
  name: trd-prd-index
  namespace: trd-frontend
  labels:
    app: index-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: index-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: index-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - index-app
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "ScheduleAnyway"
          labelSelector:
            matchLabels:
              app: index-app
      containers:
        - image: 412381775968.dkr.ecr.ap-northeast-2.amazonaws.com/trd-dockerhub:nginxindexv1.0
          name: trd-index
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /index.jsp 
              port: 80
            initialDelaySeconds: 60 
            periodSeconds: 10 
          readinessProbe:
            httpGet:
              path: /index.jsp
              port: 80
            initialDelaySeconds: 60 
            periodSeconds: 10 
            successThreshold: 1 
            failureThreshold: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trd-prd-sign
  namespace: trd-frontend
  labels:
    app: sign-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sign-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: sign-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - sign-app
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              app: sign-app
      containers:
        - image: 412381775968.dkr.ecr.ap-northeast-2.amazonaws.com/trd-dockerhub:nginxsignv1.0
          name: trd-sign
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /signup.jsp 
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10 
          readinessProbe:
            httpGet:
              path: /signup.jsp
              port: 80
            initialDelaySeconds: 60 
            periodSeconds: 10 
            successThreshold: 1 
            failureThreshold: 5  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trd-prd-login
  namespace: trd-frontend
  labels:
    app: login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: login-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - login-app
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              app: login-app
      containers:
        - image: 412381775968.dkr.ecr.ap-northeast-2.amazonaws.com/trd-dockerhub:nginxloginv1.0
          name: trd-login
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /login.jsp 
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10 
          readinessProbe:
            httpGet:
              path: /login.jsp
              port: 80
            initialDelaySeconds: 60 
            periodSeconds: 10 
            successThreshold: 1 
            failureThreshold: 5 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trd-prd-book
  namespace: trd-frontend
  labels:
    app: book-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: book-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - book-app
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "ScheduleAnyway"
          labelSelector:
            matchLabels:
              app: book-app
      containers:
        - image: 412381775968.dkr.ecr.ap-northeast-2.amazonaws.com/trd-dockerhub:nginxbookv1.0
          name: trd-book
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /product-search.jsp 
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10 
          readinessProbe:
            httpGet:
              path: /product-search.jsp
              port: 80
            initialDelaySeconds: 60 
            periodSeconds: 10 
            successThreshold: 1 
            failureThreshold: 5
