# index-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-trdindex
  namespace: trd-backend # trd-backend namespace에 volume 생성
spec:
  capacity:
    storage: 5Gi # 용량: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # 모든 데이터 플레인들이 읽고 쓸 수 있음.
  persistentVolumeReclaimPolicy: Retain # EFS의 file system id와 연결하므로 Retain 정책 설정
  storageClassName: efs-sc # storageclass.yaml file에서 정의
  csi:
    driver: efs.csi.aws.com # efs-csi-driver 설치
    volumeHandle: fs-09c306a3e1c0baea2 # file system ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-trdindex
  namespace: trd-backend # PersistentVolumeClaim 역시 같은 namespace에 생성
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi   
---
# sign-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-trdsign
  namespace: trd-backend
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09c306a3e1c0baea2
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-trdsign
  namespace: trd-backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---

# login-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-trdlogin
  namespace: trd-backend
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09c306a3e1c0baea2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-trdlogin
  namespace: trd-backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---
# book-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-trdbook
  namespace: trd-backend
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09c306a3e1c0baea2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-trdbook
  namespace: trd-backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
